# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool: Default

#container: python:2-alpine

steps:
- script: docker run python:2-alpine python -m py_compile sources/add2vals.py sources/calc.py
  displayName: 'Compile'

- publish: $(System.DefaultWorkingDirectory)/sources/*.py*
  displayName: 'Publish artifacts'

- script: docker run python:2-alpine py.test --junit-xml test-reports/results.xml sources/test_calc.py
  displayName: 'Test'

- task: PublishTestResults@2
  inputs:
    testResultsFormat: 'JUnit'
    testResultsFiles: 'test-reports/results.xml'
  displayName: 'Publish test results'

