# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool: Default

steps:
- script: docker run -v $(pwd)/sources:/sources -w / python:2-alpine python -m py_compile sources/add2vals.py sources/calc.py
  displayName: 'Compile'

- publish: sources/*.py*
  displayName: 'Publish artifacts'

- script: docker run -v $(pwd)/sources:/sources -w / python:2-alpine py.test --junit-xml sources/test-results.xml sources/test_calc.py
  displayName: 'Test'

- task: PublishTestResults@2
  inputs:
    testResultsFormat: 'JUnit'
    testResultsFiles: 'sources/test-results.xml'
  displayName: 'Publish test results'

